### PR TITLE
added IgnoreNotFound error; simplified log; README fix

### PR DESCRIPTION
**Pull request by SachinMaharana**
Signed-off-by: SachinMaharana <sachin.nicky@gmail.com>

## Description
Added IgnoreNotFound error in case unable to fetch resource, thus signalling to reconcile again. Also a TODO of the project.
simplified the log which was already provided by kubebuilder. 
fixed a missing escape character  in README.md

## Which issue # does this fix? And was it approved before you worked on it?

This adds more error handling in case unable to fetch resource, as mentioned in the TODO section of README.md

Checklist:

- [ ] Fixes issue: # 
- [ ] I waited for approval before creating this PR

Note: if the PR is for a typo, please close it and raise an issue instead.

## How Has This Been Tested?

Followed the project  test guide. Create a `kind` cluster, add docker hub registry, and tested against `make run` to verify.

`Kind` Cluster was used locally to test.

## How are existing users impacted? What migration steps/scripts do we need?
No Imapact. 

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/inlets/inlets/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by alexellis** [comment]
Hi thank you for your interest.

> Which issue # does this fix? And was it approved before you worked on it?

This section can't be ignored, please can you go ahead and follow the process? It would make things so much easier 👍✅

I'll take a look at your proposed change once it's in place and linked here

**Comment by alexellis** [comment]
> Added IgnoreNotFound error in case

I'm not sure what this means? You'll need to follow the instructions to raise an issue stating more details and the before/after behaviour.

**Comment by SachinMaharana** [comment]
Okay Alex. I am closing this pull request and instead will raise a new issue with more details, as  its not in line with the contributuion guidelines for this project.  Thanks

**Comment by alexellis** [comment]
I didn't ask you to close the PR, but you do need to create an issue and describe: what's wrong, how you fixed it, and how you've shown that the fix works.

**Pull request closed without merging**
