### PR TITLE
Fix leader-election-role rules

### PR DESCRIPTION
**Pull request by nsurleraux-railnova**
## Description

Give permission to the leader-extension-role to access coordination.k8s.io/leases

## Which issue # does this fix? And was it approved before you worked on it?

Checklist:

- [x] Fixes issue: #42 
- [x] I waited for approval before creating this PR

Note: if the PR is for a typo, please close it and raise an issue instead.

## Are you a GitHub Sponsor (Yes/No?)

Pull Requests from sponsors get prioritised and a quicker response.

Check at: https://github.com/sponsors/alexellis
- [ ] Yes
- [x] No

## How Has This Been Tested?

Tested on our production EKS cluster.

## How are existing users impacted? What migration steps/scripts do we need?
No foreseen impact.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] read the [CONTRIBUTION](https://github.com/inlets/inlets/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for signing off. We will need more details of the testing along with the manifests being regenerated. See the Makefile targets.

**Comment by nsurleraux-railnova** [comment]
I just regenerated the manifest using `make shrinkwrap`. I also just tested on my local cluster and `make deploy` that the controller deploys and runs without issue.

**Review by alexellis — APPROVED** [review]
Approved

**Comment by alexellis** [comment]
Thanks @nsurleraux-railnova I'll get this merged.

**Pull request merged**
