### PR TITLE
If you copy pasta this it breaks.

### PR DESCRIPTION
**Pull request by jjasghar**
Paul and I found this on a stream we were doing.

Signed-off-by: JJ Asghar <jjasghar@gmail.com>
Co-authored-by: Paul Czarkowski <username.taken@gmail.com>

### CODE REVIEW

**Review by alexellis — APPROVED** [review]
LGTM

**Comment by alexellis** [comment]
Thanks for picking that up. Can you confirm that arkade isn't affected?

**Comment by alexellis** [comment]
Do you have a link to your stream?

Just a note for future PRs, "tongue in cheek" and jokes don't translate well to a git log, so perhaps something a bit more objective like "Fix YAML snippet for ClusterPullSecret"?

**Comment by jjasghar** [comment]
https://youtu.be/wGVHRfeM-ZA?t=2644

**Comment by alexellis** [comment]
Thank you for the link

**Pull request merged**
