### PR TITLE
feat: delete secret when ignoring a namespace

### PR DESCRIPTION
**Pull request by eddycharly**
## Description

This PR adds secret deletion when ignoring a namespace.

When a namespace is annotated, the secret is removed from the service accounts if needed and the secret is deleted.

## Which issue # does this fix? And was it approved before you worked on it?

There is no issue created for this PR.

Although it is about excluding a namespace to be considered for injecting image pull secrets into service accounts.
When one namespace get excluded a posteriori, injected image pull secrets should be removed from this particular namespace to honor exclusion request.

Checklist:

- [ ] Fixes issue: # 
- [ ] I waited for approval before creating this PR

Note: if the PR is for a typo, please close it and raise an issue instead.

## How Has This Been Tested?

This has been tested in our own cluster (we are using registry-creds to pull dockerhub images).

## How are existing users impacted? What migration steps/scripts do we need?

Existing users should not be impacted at all.
There are no migration steps to be applied.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/inlets/inlets/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by eddycharly** [comment]
@alexellis thanks for the great work, any idea why the build is failing ? Looks like there's something wrong with kind.

**Comment by eddycharly** [comment]
@alexellis any reason why you closed the PR ?

**Comment by alexellis** [comment]
I was closing old PRs that had been left inactive, but this one looks like it should still be open.

Can you please go ahead and fill out the PR template?

I'd also like to see your code with less refactoring, this should be a simple change, and not involve so many changed lines.

**Comment by eddycharly** [comment]
I'll fill in the template, sure.

Regarding code changes, not sure how you would like me to implement it. I had to add `deleteSecret` and `removeSecretFromSA` primitives as they didn't exist.
Taking care of calling them when a namespace gets excluded takes a bit of lines of code too.

Can you suggest line changes that are irrelevant so that i can get the idea of what was unnecessarily changed ?

**Pull request closed without merging**
